import "./documentPreview.css";

export default function DocumentPreview({ content, agreementType, onClose }) {
  return (
    <div className="document-preview">
      <div className="preview-header">
        <h3>Generated {agreementType}</h3>
        <button onClick={onClose} className="close-btn">
          ✕
        </button>
      </div>

      <div className="document-content">
        <div className="document-header">
          <h1>{agreementType}</h1>
          <p className="document-date">
            Generated on: {new Date().toLocaleDateString()}
          </p>
          <hr className="document-divider" />
        </div>

        <div className="document-body">
          {content.split("\n").map((paragraph, index) => (
            <p key={index} className="document-paragraph">
              {paragraph}
            </p>
          ))}
        </div>

        <div className="document-footer">
          <p className="footer-note">
            <strong>Disclaimer:</strong> This document is generated by AI and
            should be reviewed by a legal professional before use.
          </p>
        </div>
      </div>
    </div>
  );
}
