from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io
from datetime import datetime
from docx import Document as DocxDocument
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import os

def generate_pdf(content, agreement_type, metadata=None):
    """Generate PDF from content"""
    buffer = io.BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(buffer, pagesize=A4, 
                          rightMargin=72, leftMargin=72,
                          topMargin=72, bottomMargin=72)
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#2c3e50')
    )
    
    # Heading style
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=12,
        spaceBefore=12,
        spaceAfter=6,
        textColor=colors.HexColor('#34495e')
    )
    
    # Normal style
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        leading=14  # Line spacing
    )
    
    # Build story
    story = []
    
    # Add title
    story.append(Paragraph(agreement_type, title_style))
    story.append(Spacer(1, 20))
    
    # Add metadata if available
    if metadata:
        meta_data = [
            ["Document Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Agreement Type", agreement_type],
            ["Sri Lankan Legal Document", "AI-Assisted Generation"]
        ]
        
        # Add key user details
        key_fields = ['employeeName', 'employerName', 'sellerName', 'buyerName', 
                     'serviceProvider', 'client', 'partyAName', 'partyBName']
        
        for field in key_fields:
            if field in metadata and metadata[field]:
                meta_data.append([field.replace('Name', '').title(), str(metadata[field])])
        
        if len(meta_data) > 3:
            meta_table = Table(meta_data, colWidths=[2*inch, 3*inch])
            meta_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6'))
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 20))
    
    # Add content
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 12))
        elif line.upper() == line and len(line) < 50 and ':' not in line:  # Likely a heading
            story.append(Paragraph(line, heading_style))
        else:
            story.append(Paragraph(line, normal_style))
    
    # Add footer with disclaimer
    story.append(Spacer(1, 30))
    disclaimer = Paragraph(
        "<b>Legal Disclaimer:</b> This document was generated by AI and should be reviewed by a qualified legal professional in Sri Lanka before use. This is not legal advice.",
        ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
    )
    story.append(disclaimer)
    
    # Build PDF
    doc.build(story)
    
    # Get PDF bytes
    buffer.seek(0)
    return buffer

def generate_docx(content, agreement_type):
    """Generate DOCX from content"""
    buffer = io.BytesIO()
    
    # Create document
    doc = DocxDocument()
    
    # Add title
    title = doc.add_heading(agreement_type, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add generation date
    date_para = doc.add_paragraph()
    date_run = date_para.add_run(f"Generated on: {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}")
    date_run.italic = True
    date_run.font.size = Pt(10)
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph()  # Add empty paragraph
    
    # Add content
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            doc.add_paragraph()  # Empty paragraph for blank lines
        elif line.upper() == line and len(line) < 50 and ':' not in line:  # Likely a heading
            heading = doc.add_heading(line, level=2)
        else:
            para = doc.add_paragraph(line)
            para.style.font.size = Pt(11)
            # Justify text for body paragraphs
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    
    # Add page break before footer
    doc.add_page_break()
    
    # Add footer with disclaimer
    footer = doc.sections[0].footer
    footer_para = footer.paragraphs[0]
    footer_run = footer_para.add_run("Disclaimer: This document was generated by AI and should be reviewed by a qualified legal professional in Sri Lanka before use. This is not legal advice.")
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(128, 128, 128)
    
    # Save to buffer
    doc.save(buffer)
    buffer.seek(0)
    return buffer